# -*- coding: utf-8 -*-
"""easy-ocr

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10lf31QYtDMb6HQk4BhNsJg_R5-4laLwy
"""

!pip install easyocr

pip install cv2

import matplotlib.pyplot as plt
import cv2
import easyocr
from pylab import rcParams
from IPython.display import Image
rcParams['figure.figsize'] = 8, 16

!pip uninstall opencv-python-headless==4.5.5.62

!pip install opencv-python-headless==4.5.2.52

reader = easyocr.Reader(['en'])

Image("/content/00040534.png")

output = reader.readtext('/content/00040534.png')

output

cord = output[-1][0]

x_min, y_min = [int(min(idx)) for idx in zip(*cord)]

x_max, y_max = [int(max(idx)) for idx in zip(*cord)]

image = cv2.imread('/content/00040534.png')
cv2.rectangle(image,(x_min,y_min),(x_max,y_max),(0,0,255),2)
plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))

